[package]
name = "mitex"
description = "MiTeX is a TeX2Typst converter."
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

mitex-parser = { path = "../mitex-parser" }
rowan = "0.15.13"
bitflags = "2.4.1"
